CREATE TABLE simulation_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL,
    seed BIGINT NOT NULL,
    world_width INTEGER NOT NULL,
    world_height INTEGER NOT NULL,
    ticks_completed BIGINT NOT NULL,
    initial_organism_count BIGINT NOT NULL,
    ending_organism_count BIGINT NOT NULL,
    termination_reason TEXT NOT NULL,
    config_json JSONB NOT NULL,
    git_commit TEXT,
    git_dirty BOOLEAN
);

CREATE TABLE organism_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    simulation_run_id BIGINT NOT NULL,
    organism_id BIGINT NOT NULL,
    parent_organism_id BIGINT,
    birth_tick BIGINT NOT NULL,
    mutated_weight_count BIGINT
        CHECK (
            mutated_weight_count IS NULL
            OR mutated_weight_count >= 0
        ),
    death_tick BIGINT,
    lifespan BIGINT NOT NULL,
    initial_energy DOUBLE PRECISION NOT NULL,
    final_energy DOUBLE PRECISION NOT NULL,
    peak_energy DOUBLE PRECISION NOT NULL,
    energy_consumed DOUBLE PRECISION NOT NULL,
    distance_moved BIGINT NOT NULL,
    genome JSONB NOT NULL,

    FOREIGN KEY (simulation_run_id)
        REFERENCES simulation_runs(id),
    UNIQUE (simulation_run_id, organism_id)
);

CREATE INDEX idx_organism_results_parent
ON organism_results (simulation_run_id, parent_organism_id);
